#pragma once
#define UAC_CLOCK 4
#define UAC_CAPTURE_CLOCK 0x14
#define UAC_PLAYBACK_INPUT 1
#define UAC_PLAYBACK_FEATURE 2
#define UAC_PLAYBACK_OUTPUT 3
#define UAC_CAPTURE_INPUT 0x11
#define UAC_CAPTURE_FEATURE 0x12
#define UAC_CAPTURE_OUTPUT 0x13
enum { ITF_AUDIO_CONTROL, ITF_PLAYBACK, ITF_CAPTURE, ITF_HID, ITF_TOTAL };
#define ULL_AUDIO_AC_BODY_LEN (2*TUD_AUDIO_DESC_CLK_SRC_LEN + 2*TUD_AUDIO_DESC_INPUT_TERM_LEN + 2*TUD_AUDIO_DESC_OUTPUT_TERM_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_TWO_CHANNEL_LEN + TUD_AUDIO_DESC_FEATURE_UNIT_ONE_CHANNEL_LEN)
#define ULL_AUDIO_AS_LEN (2*TUD_AUDIO_DESC_STD_AS_INT_LEN + TUD_AUDIO_DESC_CS_AS_INT_LEN + TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN)
#define ULL_AUDIO_DESCRIPTOR_LEN (TUD_AUDIO_DESC_IAD_LEN + TUD_AUDIO_DESC_STD_AC_LEN + TUD_AUDIO_DESC_CS_AC_LEN + ULL_AUDIO_AC_BODY_LEN + 2*ULL_AUDIO_AS_LEN + TUD_AUDIO_DESC_STD_AS_ISO_FB_EP_LEN)
